// Carga inicial de la tabla maestra `units` (Unidades y Servicios HUAP).
// Lista provista por el Comité de Innovación; puede contener nombres
// repetidos porque un mismo servicio aparece bajo más de una subdirección
// en el organigrama — se deduplica en seed.ts antes de insertar.
export const HUAP_UNITS: string[] = [
  'Director',
  'Oficina de Partes',
  'Auditoria',
  'Análisis Clínico GRD',
  'Comunicaciones y Relaciones Públicas',
  'Calidad Percibida',
  'IAAS',
  'Calidad y Seguridad del Paciente',
  'Asesoría Jurídica',
  'Salud del Trabajador',
  'Proyectos',
  'Departamento de Planificación y Control de Gestión',
  'Control de Gestión',
  'Estadística',
  'Participación Ciudadana',
  'Departamento de Formación, Investigación y Docencia',
  'Relación Asistencial Docente y Formación',
  'Investigación',
  'Biblioteca',
  'Simulación y Docencia Continua',
  'Subdirector/a de Gestión Clínica',
  'Epidemiología Clínica',
  'Departamento Gestión de la Demanda',
  'Gestión de Pacientes',
  'Servicio Social de Pacientes',
  'Hospitalización Domiciliaria',
  'GES',
  'Gestión de Convenios Clínicos',
  'Rehabilitación y Gestión Funcional',
  'Anatomía Patológica',
  'Banco de Sangre',
  'Imagenología',
  'Procuramiento de Órganos y Tejidos',
  'Laboratorio Clínico',
  'Farmacia Clínica',
  'Farmacia',
  'Nutrición',
  'Emergencia Hospitalaria',
  'Urgencia Dental y Cirugía Maxilofacial',
  'UCI - MQ',
  'Quemados',
  'UTI - MQ',
  'Cuidados Medios MQ',
  'Clínica HUAP',
  'Pabellón y Anestesia',
  'Traumatología',
  'Angiografía',
  'Neurocirugía',
  'Urología',
  'Cirugía Diferida',
  'Cirugía',
  'Endoscopía',
  'Oncología',
  'Psiquiatría y Psicología de Enlace',
  'Infectología',
  'Medicina Paliativa',
  'Nefrología',
  'Cardiología',
  'Neurología',
  'Fisiatría',
  'Subdirector/a de Gestión del Cuidado',
  'Departamento de Gestión en Procesos Clínicos - Asistenciales',
  'Buenas Prácticas Clínicas',
  'Accesos Vasculares',
  'Gestión en Insumos Clínicos y Equipamiento MQ',
  'Distribución y Gestión de Ropa Clínica',
  'Jefe Turno A',
  'Jefe Turno B',
  'Jefe Turno C',
  'Jefe Turno D',
  'Emergencia Hospitalaria',
  'Urgencia Dental y Cirugía Maxilofacial',
  'UCI - MQ',
  'Quemados',
  'UTI - MQ',
  'Cuidados Medios MQ 3°',
  'Cuidados Medios MQ 4°',
  'Cuidados Medios MQ 6°',
  'Clínica HUAP',
  'Hospitalización Domiciliaria',
  'Pabellón',
  'Angiografía',
  'Esterilización',
  'Cirugía - Urología - Neurocirugía',
  'Endoscopía',
  'Control Post Alta',
  'Psiquiatría y Psicología de Enlace',
  'Medicina Paliativa',
  'Nefrología',
  'Cardiología',
  'Neurología',
  'Subdirector/a de Gestión Administrativa y Financiera',
  'Control de Presupuesto',
  'Admisión',
  'Departamento de Finanzas',
  'Contabilidad',
  'Tesorería',
  'Cobranzas',
  'Análisis Financiero',
  'Departamento de Abastecimiento',
  'Licitaciones',
  'Gestión de Contratos',
  'Adquisiciones',
  'Aprovisionamiento y Distribución',
  'Departamento de Tecnología de la Información',
  'Operación y Soporte',
  'Desarrollo Tecnológico',
  'Departamento de Recursos Físicos',
  'Equipos Médicos',
  'Equipos Industriales',
  'Infraestructura',
  'Departamento de Servicios Generales',
  'Operaciones',
  'Servicios Básicos',
  'Inventario de Bienes',
  'Subdirector/a de Gestión y Desarrollo de las Personas',
  'Gestión Procesos y Mejora Continua',
  'Departamento Gestión de las Personas',
  'Remuneraciones',
  'Honorarios',
  'Administración de Personas',
  'Control de la Jornada',
  'Departamento Calidad de Vida',
  'Prevención de Riesgos',
  'Sala Cuna y Cuidados Infantiles',
  'Bienestar al Personal',
  'Departamento Gestión del Cambio',
  'Desarrollo Organizacional',
  'Capacitación',
  'Reclutamiento y Selección',
];
